import React, { Component } from 'react';
import LogoIcon from '../img/logo.png';
import { Nav} from 'react-bootstrap';

class Privacypolicy extends Component {
  render() {
    return (
        <section className="privacy">
            <div className="container">
            <div className="row">
                    <div className="col-lg-12">
                    <Nav.Link className="logo" href="/"><img src={LogoIcon} alt="logo" /></Nav.Link>
                    </div>
                </div>
                <div className="row">
                    <div className="col-lg-12">
                        <h1>The Global Tourism and Resorts</h1>
                        <h3>PrivacyPolicy</h3>
                    </div>
                </div>
                <div className="row">
                    <div className="col-lg-12">
                        <p>The Global Tourism and Resorts, collects, stores, and uses your personal information as a data controller in connection with and in order to provide and develop The Global Tourism and Resortsproducts,  mobile  applications,  services  and  websites  (together  “Services”)  according  to  this privacy policy (“Privacy Policy”)</p>
                        <p>For questions and information about Privacy Policy and data subject’s rights, please contact us at <a href="mailto:accounts@exploreholidays.in?Subject=Hello%20again" target="_top">accounts@exploreholidays.in</a> or  alternatively  at The  Global  Tourism  and  Resorts, SCO  188-190, GF, Sector 34, Chandigarh, India-160034</p>
                        <p>For information about our privacy practices related to data from children, please see “Special Note About Children’s Privacy” below.</p>
                        <p>All The Global Tourism and Resorts Services are governed by thisPrivacy Policy and by using or accessing a Service You give consent to the processing, use and disclosure of your data. Please do not install or use the Services if you do not agree to this Privacy Policy.</p>
                        <p>The Global Tourism and Resortsreserves the right to modify this Privacy Policy. Your continued use of Services will signify your acceptance of the changes to this Privacy Policy.</p>
                        <h3>1. How We Collect Your data</h3>
                        <p>Likely  situations  when  you  make  personal  data  available  to The  Global  Tourism  and  Resortsinclude, but are not limited to: (i) by visiting our websites, (ii) registration for Services, contests and special events; (iii) accessing Services using a third party ID, such as social networking sites or gaming services; (iv) subscribing to newsletters; (v) purchasing a product or services through 
visiting  us (vi) using “tell a friend,” “email this page,” or other similar features; (vii) requesting technical support; and (viii) otherwise through use of The Global Tourism and Resorts Services where personal data is required for use and/or participation.</p>
                    <p>The  data  we  process  on  you  may  include,  but  is  not  limited  to:  email  address,  device  ID,  IP-address, user names and passwords.</p>
                    <p>The Global Tourism and Resorts may supplement your data with data received from third parties in connection with demographic, advertisement, market and other analytics surveys or services.</p>
                    <h3>2. Ad Serving Technology</h3>
                    <p>The Global Tourism andResortsreserves the right to use and disclose the collected, non-personal data  for  purposes  of  advertising  by The  Global  Tourism  and  Resorts or  our partners  and contractors.</p>
                    <p>The Global Tourism and Resorts may employ third party ad serving technologies that use certain methods to collect information as a result of ad serving through Services.</p>
                    <p>The  Global  Tourism  and  Resortsor  third  parties operating  the  ad  serving  technology may  use demographic and geo-location information (for more information regarding use of Location Data see below Section 3) as well as information logged from your hardware or device to ensure that relevant  advertising  is  presented  within  the  Service. The  Global  Tourism  and  Resortsor  third parties may collect and use data, for such purposes, including but not limited to, data such as IP address,  Device  ID,  MAC  address,  installed  software,  application  usage  data,  hardware  type, Operating System information, browser information, unique identifiers in browser cookies, Flash cookies,  and  HTML5  local  storage,  Internet  and  on-line  usage  information  and  in-game information.</p>
                    <p>The foregoing data may be used and disclosed in accordance with this Privacy Policy.</p>
                    <p>If you want to be certain that no behaviorally targeted advertisements are displayed to you, please do not use or access the Services.Some services may include the use of in-game advertisements or brand placement. Such ads or sponsorships will be noted as such within the services.</p>
                    <p>Additionally please note that if you “opt out” it does not mean that you will no longer receive advertising. It just means that the advertising you see displayed will not be customized to you and your interests and may be less relevant to you.</p>
                    <h3>3. Location Data</h3>
                    <p>To  the  extent The  Global  Tourism and  Resortsmakes  location enabled  Services available and you use such Services, The Global Tourism and Resortsmay collect and process your location data  to  provide  location  related  Services  and  advertisements.  For  example,  some  add-ons  or offers may be available at dedicated locations. The location data is processed and stored only for the duration that is required for the provision of the location related Services.</p>
                    <p>The Global Tourism and Resortsmay use, depending on the service (1) IP-based location based on  the  IP  address  presented  by  the  end-user,  (2)  fine  geo-location  data  based  on  coordinates obtained from a mobile device’s GPS radio, or (3) coarse, network-based geo-location data based on proximity of network towers or the location of WiFi networks.</p>
                    <p>Your  fine,  GPS-based geo-location  is not  accessed  without  your  consent.  Notwithstanding The Global Tourism and Resortspartners who are providing location related parts of the Service, The Global Tourism and Resortswill not share your GPS geo-location with third parties without your consent.</p>
                    <h3>4. Analytics</h3>
                    <p>The Global Tourism and Resortsuses your information to perform its own analytics and to enable analytics provided by third parties. We use analytical information for supporting business analysis and  operations,  business  intelligence,  product  development,  improving  products  and  services, personalizing content, providing advertising, and making recommendations. The Global Tourism and  Resortsmay  also  use  third-parties,  such  as  a  Google  Analytics  in  order  to  develop  and analyze use of the Services.</p>
                    <h3>5. Friends</h3>
                    <p>If you choose to use The Global Tourism and Resorts“tell a friend” or “Share” or a similar service about The Global Tourism and ResortsServices, The Global Tourism and Resortsmay store your friend’s name and contact details that you provide to The Global Tourism and Resorts.</p>
                    <p>Please note that certain features of the Services may be able to connect to your social networking sites to obtain additional information about you. In such cases, The Global Tourism and Resortsmay  be  able  to  collect  certain  information  from  your  social  networking profile  when  your  social networking site permits it, and when you consent to allow your social networking site to make that information available to The Global Tourism and Resorts. This information may include, but is not limited to, your name, profile picture, gender, user ID, email address, your country, your language, your time zone, the organizations and links on your profile page, the names and profile pictures of your social networking site “friends” and other information you have included in your social networking site profile. The Global Tourism and Resortsmay associate and/or combine as well as use information collected by The Global Tourism and Resortsand/or obtained through such social networking sites.</p>
                    <h3>6. Disclosure and Transfer of Personal Data</h3>
                    <p>Personal data may be disclosed to third parties in accordance with applicable legislation and this Privacy Policy.</p>
                    <p>The Global Tourism and Resortsmay use third parties to collect and process personal data on The  Global  Tourism  and  Resortsbehalf  and  in  according  to The  Global  Tourism  and  Resortsinstructions. The Global Tourism and Resortsis not liable for the acts and omissions of these third parties, except as provided by mandatory law.</p>
                    <h3>7. Data Retention and Correctness</h3>
                    <p>The Global Tourism and Resortsretains the collected data for the period necessary to fulfill the purposes outlined in this Privacy Policy unless a longer retention period is required or permitted by  law.  Thereafter The  Global  Tourism  and  Resortsdeletes  all  aforementioned  data  in  its possession within a reasonable timeframe. The Global Tourism and Resortsdoes not verify the correctness of personal data.</p>
                    <p>Please note that some data may be further retained if necessary to resolve disputes, enforce The Global Tourism and Resortsuser agreements, and comply with technical and legal requirements and constraints related to the security, integrity and operation of Services.</p>
                    <h3>8. Cookies, beacons and tracking</h3>
                    <p>The Services may use “cookies” and other technologies such as pixel tags, local shared objects, hardware-based  device  identifiers,  Operating  System-based  identifiers,  clear  GIFs  and  web beacons. The  Global  Tourism  and  Resortstreats  information  collected  by  cookies  and  similar technologies as non-personal data.</p>
                    <p>Cookies: A “cookie” is a small file stored by your browser when told to do so by a website. Typically websites place a number of different cookies on an end-user’s machine. Some of the cookies are “1st Party,” from the website itself, and others are “3rd party,” belonging to advertising and analytics  entities  or  social  networks. The  Global  Tourism  and  Resortscookies  do  not  include personal  data  and  are typically used to quickly identify your device and to “remember” your browser  during  subsequent  visits  for  purposes  of  functionality,  preferences,  and  website performance. You can disable cookies or set your browser to alert you when cookies are being sent to your device; however, disabling cookies may affect your ability to use the Services.</p>
                    <p>Flash  cookies  &  HTML5: The  Global  Tourism  and  Resortsmay  also  use  Flash  cookies  (local shared objects) and HTML5 local storage. Flash cookies are small files similar to browser cookies, but  which  are  not  stored  in  the  browser  and  can  also  be  used  to  remember  your  settings,  to personalize the look and feel of the Services, or for advertising and analytics.</p>
                    <p>Web Beacons and pixel tags: A “web beacon” or a “pixel tag” is an electronic image (often not visible  to  the  end-user)  that  allows The  Global  Tourism  and  Resortsto  count  users  who  have visited certain pages or viewed certain advertisements. Additionally, e-mails and other electronic communications The Global Tourism and Resortssends to you may contain pixel tags that enable The Global Tourism and Resortsto track your usage of the communication, including whether the communication was opened and/or what links were followed, if any.</p>
                    <h3>9. Third Party Terms and Conditions</h3>
                    <p>Please note that your access to and use of the Services may be subject to certain third party terms and conditions and The Global Tourism and Resortsis not liable for any such third parties’ use of your personal data.</p>
                    <p>Certain  Services  that The  Global  Tourism and  Resortsmay  offer,  such  as multiplayer  gaming, social  networking  and  gaming  console  services,  may  use  third  party  services  to  provide authentication for the Services with a gaming console ID, social networking ID, or gaming network account. In connection with such use, certain personally identifiable user and/or membership data may be transferred automatically to and from The Global Tourism and Resorts.</p>
                    <p>The Global Tourism and Resortsmay disclose your personal data to third parties inconnection with  a  corporate  merger,  consolidation,  restructuring,  the  sale  of  substantially  all of The  Global Tourism and Resortsstock and/or assets or other corporate change, including, without limitation, during the course of any due diligence process provided, however, that this Privacy Policy shall continue to govern such personal data.</p>
                    <h3>10. Safeguards</h3>
                    <p>The  Global  Tourism  and  Resortsfollows  generally  accepted  industry  standards  and  maintains reasonable safeguards to attempt to ensure the security, integrity and privacy of the information in The Global Tourism and Resortspossession.</p>
                    <h3>11. Other</h3>
                    <p>You  may  choose  to  disclose  data  aboutyourself  in  the  course  of  contributing  user  generated content to the Services</p>
                    <p>Any  data  that  you  disclose  in  any  of  these  forums,  blogs,  chats  or  the  like  will  become  public information, and there is no expectation of privacy or confidentiality with respect to that data.</p>
                    <p>The Global Tourism and Resortsmay store and/or transfer your personal data to its affiliates and partners in accordance with mandatory legislation and this Privacy Policy.</p>
                    <h3>12. Special Note about Children’s Privacy</h3>
                    <p>The Global Tourism and Resortsdoes not knowingly collect personal information from children under 13 years of age. If The Global Tourism and Resortslearns that The Global Tourism and Resortshas inadvertently gathered personal data from children under 13 years of age, The Global Tourism and Resortswill take reasonable measures to promptly delete such personal data from The Global Tourism and Resortsrecords.</p>
                    <p>The  Global  Tourism  and  Resortsunderstands  the  need  to  provide  extra  privacy  protections  to users  who  are  children.  To  that end,  features and  services  such  as  social  networking  plug-ins, behaviorally targeted advertising, and collection of data for the purpose of building user profiles are not available to users under 13. The Global Tourism and Resortsalso does not allow our third party  partners  who  engage  in  such  practices  to  access  personally  identifiable  data  from  users under 13.</p>
                    <p>The Global Tourism and Resortsand its partners do collect non-personally identifiable data from children.  This  includes,  for example,  collection  of  IP-based  geolocation  data  to  ensure  that  the product, service or features served comply with applicable laws of that nation.</p>
                    <p>The Global Tourism and Resortsand its partners also collect data to assess general information about  the  use  of  products,  such  as  the  number  of  visitors  to  our  sites  and  services  and  which sections of a site or service are popular. The Global Tourism and Resortsalso uses this data to provide  contextually-relevant  advertising  to  users,  to  prevent  usersfrom  seeing  the  same  ad repeatedly, and to allow users to personalize their experience on the site or service (for example, to save a high score in a game). The Global Tourism and Resortsand its partners may also use cookies, pixels, hardware-based identifiers, Operating System-based identifiers, and software-set identifiers, to manage and measure the performance of advertising.</p>
                    <p>Please note that The Global Tourism and Resortspartners may have their own policies related to tracking  technologies  for  analytics  and  ad-serving  purposes.  While The  Global  Tourism  and Resortsrequires  that  companies  comply  with The  Global  Tourism  and  Resortsprivacy  policy before The Global Tourism and Resortsallows those companies to access our sites and services, The Global Tourism and Resortsdoes not actually control third-party data collection and use.</p>
                    <p>If you have additional questions about The Global Tourism and ResortsPrivacy Practices related to children under the age of 13, please contact us at <a href="mailto:accounts@exploreholidays.in?Subject=Hello%20again" target="_top">accounts@exploreholidays.in</a>, or alternatively at The Global Tourism and Resorts, SCO 188-190, GF, Sector 34, Chandigarh, India-160034</p>
                    <h3>13. Further information</h3>
                    <p>This Privacy Policy is governed by Indian Law excluding its choice of law provisions.</p>
                    <p>The  Global  Tourism  and  Resortsmakes  good  faith  efforts  to  enable  you  to  review,  update  or correct your personal data in The Global Tourism and Resortspossession.</p>
                    <p>The Global Tourism and Resortswill need sufficient information from you to establish your identity and to verify your access request, and also to assist us in handling your request.</p>
                    <p>ThisdocumentwaslastupdatedonMarch10,2018</p>
                    </div>
                </div>
            </div>
        </section>
        );
  }
}  
export default Privacypolicy;